# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951c8ef9ab669a6e167a5f7b54d10ea183c3d4442e8fe38c9e12a824dcff4900258e23365790dc7bbe7e6bb1e51c2913adc34c90021326616909421426561337

test:
  secret_key_base: c57397fcb12b275da94ab9c1a37a798181cea28522ba122e8357d9666d86e162c6b61d57e0571a433036f051cd633ef396e555412486609341c2ef4a0ea76d93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
